---
title: Amanda Ding
author: Amanda Ding
email: amanda.y.ding@gmail.com
description: ''
baseurl: ''
url: amandading.me
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
